### ISSUE TITLE
Dark Elixir Drill should be available at TH7 but isn't

### ISSUE THREAD

**Issue by dgeisbush** [straxhaber/clashofclans-calculator#3]
I'm having a problem with this otherwise excellent tool. I don't see the Dark Elixir Drill as buildable at TH7.

**Comment by straxhaber** [comment]
Thanks. I haven't been maintaining it very actively. I'll take a look and see if I can update it quickly.

**Comment by straxhaber** [comment]
I just updated it. Let me know if you notice anything else.
